### Get all books

GET http://localhost:8080/books
Accept: application/json

<> 2023-10-20T150022.200.json
<> 2023-10-20T150008.200.json

### Create a bookEntity

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Lord of the Rings"
}

###